accounts/urls.py
from django.urls import path
from accounts.views import login_user, logout_user, signup_user

urlpatterns = [
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path("signup/", signup_user, name="signup"),
]

projects/urls.py
#
from django.urls import path
from projects.views import (
    list_projects,
    show_project,
    create_project,
)

urlpatterns = [
    path("", list_projects, name="list_projects"),
    path("<int:id>/", show_project, name="show_project"),
    path("create/", create_project, name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import create_task, show_my_tasks

urlpatterns = [
    path("create/", create_task, name="create_task"),
    path("mine/", show_my_tasks, name="show_my_tasks"),
]

tracker/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include


def redirect_to_home(request):
    return redirect("list_projects")


urlpatterns = [
    path("", redirect_to_home, name="home"),
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    owner = models.ForeignKey(
        User,
        related_name="projects",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Project

# Create your models here.


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False, blank=True)
    project = models.ForeignKey(
        Project,
        related_name="tasks",
        on_delete=models.CASCADE,
    )
    assignee = models.ForeignKey(
        User,
        related_name="tasks",
        on_delete=models.CASCADE,
        null=True,
    )

accounts/forms.py
from django import forms


class AccountLoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )


class AccountSignupForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )
    password_confirmation = forms.CharField(
        max_length=150,
        widget=forms.PasswordInput,
    )

projects/forms.py
from django.forms import ModelForm
from projects.models import Project


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = [
            "name",
            "description",
            "owner",
        ]

tasks/forms.py
from django.forms import ModelForm
from tasks.models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = [
            "name",
            "start_date",
            "due_date",
            "project",
            "assignee",
            "is_completed",
        ]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from accounts.forms import AccountLoginForm, AccountSignupForm

# Create your views here.


def login_user(request):
    if request.method == "POST":
        form = AccountLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("home")
    else:
        form = AccountLoginForm()

    context = {"form": form}

    return render(request, "accounts/login.html", context)


def logout_user(request):
    logout(request)
    return redirect("login")


def signup_user(request):
    if request.method == "POST":
        form = AccountSignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            password_confirmation = form.cleaned_data["password_confirmation"]

            if password == password_confirmation:
                signed_up_user = User.objects.create_user(
                    username=username,
                    password=password,
                )
                login(request, signed_up_user)
                return redirect("list_projects")
            else:
                form.add_error("password", "the passwords do not match")
    else:
        form = AccountSignupForm

    context = {"form": form}

    return render(request, "accounts/signup.html", context)

projects/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from projects.models import Project
from projects.forms import ProjectForm

# Create your views here.


@login_required
def list_projects(request):
    project_list = Project.objects.filter(owner=request.user)
    context = {"project_list": project_list}
    return render(request, "projects/list_projects.html", context)


@login_required
def show_project(request, id):
    this_project = Project.objects.get(pk=id)
    context = {"this_project": this_project}
    return render(request, "projects/project_detail.html", context)


@login_required
def create_project(request):
    errors = {}
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("list_projects")
        else:
            errors = form.errors
    else:
        form = ProjectForm()

    users = User.objects.all()
    context = {"form": form, "users": users, "errors": errors}
    return render(request, "projects/create_project.html", context)

tasks/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from tasks.forms import TaskForm
from tasks.models import Task
from projects.models import Project

# Create your views here.


@login_required
def create_task(request):
    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("list_projects")
    else:
        form = TaskForm()
    projects = Project.objects.all()
    assignees = User.objects.all()
    context = {"form": form, "projects": projects, "assignees": assignees}

    return render(request, "projects/create_task.html", context)


@login_required
def show_my_tasks(request):
    my_tasks = Task.objects.filter(assignee=request.user)
    context = {"my_tasks": my_tasks}
    return render(request, "projects/show_my_tasks.html", context)

accounts/templates/accounts/login.html
<!-- the login page for accounts (USERS!!!)-->
{% extends 'base.html' %}

<!---->
{% block title %} Accounts {% endblock title %}
<!---->
{% block content %}
<main class="mx-auto max-w-4xl">
  <div>
    <h1
      class="my-6 text-center text-4xl font-bold text-slate-900 dark:text-white sm:text-5xl"
    >
      Login
    </h1>
    <div class="flex justify-center lg:block lg:justify-left">
      <form
        method="post"
        class="items-left mx-auto flex max-w-4xl flex-col gap-4 text-2xl sm:text-3xl"
      >
      {% csrf_token %}
      <label for="username">Username:</label>
      <!--not sure about ID-->
      <input
        type="text"
        id="username"
        name="username"
        required
        minlength="3"
        maxlength="60"
        placeholder="Your Username"
        class="min-w-[240px] w-1/3 rounded-xl border border-solid border-slate-900 p-3 text-2xl text-black dark:border-none sm:text-3xl"
      />
      <label for="password">Password:</label>
      <input
        type="password"
        id="password"
        name="password"
        required
        minlength="3"
        maxlength="60"
        placeholder="Your Password"
        class="min-w-[240px] w-1/3 rounded-xl border border-solid border-slate-900 p-3 text-2xl text-black dark:border-none sm:text-3xl"
      />
      <button
        class="mt-6 w-48 rounded-xl border border-solid border-slate-900 bg-teal-700 p-3 text-white hover:bg-teal-600 active:bg-teal-500 dark:border-none"
      >
        Login
      </button>
    </form>
  </div>
</main>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

<!---->
{% block title %} Accounts {% endblock title %}
<!---->
{% block content %}
<main class="mx-auto max-w-4xl">
  <div>
    <h1
      class="my-6 text-center text-4xl font-bold text-slate-900 dark:text-white sm:text-5xl"
    >
      Signup
    </h1>
    <div class="flex justify-center lg:block lg:justify-left">
      <form
        method="post"
        class="items-left mx-auto flex max-w-4xl flex-col gap-4 text-2xl sm:text-3xl"
      >
        {% csrf_token %}
        <label for="username">Username:</label>
        <!--not sure about ID-->
        <input
          type="text"
          id="username"
          name="username"
          required
          minlength="3"
          maxlength="60"
          placeholder="Your Username"
          class="min-w-[240px] w-1/3 rounded-xl border border-solid border-slate-900 p-3 text-2xl text-black dark:border-none sm:text-3xl"
        />
        <label for="password">Password:</label>
        <input
          type="password"
          id="password"
          name="password"
          required
          minlength="3"
          maxlength="60"
          placeholder="Your Password"
          class="min-w-[240px] w-1/3 rounded-xl border border-solid border-slate-900 p-3 text-2xl text-black dark:border-none sm:text-3xl"
        />

        <label for="password_confirmation">Type Password Again:</label>
        <input
          type="password"
          id="password_confirmation"
          name="password_confirmation"
          required
          minlength="3"
          maxlength="60"
          placeholder="Confirm PW..."
          class="min-w-[240px] w-1/3 rounded-xl border border-solid border-slate-900 p-3 text-2xl text-black dark:border-none sm:text-3xl"
        />
        <button
          class="mt-6 w-48 rounded-xl border border-solid border-slate-900 bg-teal-700 p-3 text-white hover:bg-teal-600 active:bg-teal-500 dark:border-none"
        >
          Signup
        </button>
      </form>
    </div>
  </div>
</main>
{% endblock content %}

projects/templates/base.html
{% load static tailwind_tags %}
<!--NECESSARY?? yes.-->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock title %}</title>
    {% tailwind_css %}
    <script src="{% static '/js/main.js' %}" defer></script>
  </head>

  <body class="min-h-screen bg-slate-50 dark:bg-black dark:text-white">
    <header class="sticky top-0 z-10 bg-teal-700 text-white">
      <section class="mx-auto flex max-w-4xl items-center justify-between p-4">
        <h1 class="text-3xl font-medium">
          <a href="#some-top-anchor">🗒️ Jonny's Tasks</a>
        </h1>
        <div>
          <button
            id="hamburger-button"
            class="relative h-8 w-8 cursor-pointer text-3xl md:hidden"
          >
            <!-- &#9776; -->
            <div
              class="absolute top-4 -mt-0.5 h-1 w-8 rounded bg-white transition-all duration-500 before:absolute before:h-1 before:w-8 before:-translate-x-4 before:-translate-y-3 before:rounded before:bg-white before:transition-all before:duration-500 before:content-[''] after:absolute after:h-1 after:w-8 after:-translate-x-4 after:translate-y-3 after:rounded after:bg-white after:transition-all after:duration-500 after:content-['']"
            ></div>
          </button>
          <nav class="hidden space-x-8 text-xl sm:block" aria-label="main">
            {% if user.is_authenticated %}
            <a href="{% url 'show_my_tasks' %}" class="hover:opacity-90"
              >My tasks</a
            >
            <a href="{% url 'list_projects' %}" class="hover:opacity-90"
              >My projects</a
            >
            <a href="{% url 'logout' %}" class="hover:opacity-90">Logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="hover:opacity-90">Login</a>
            <a href="{% url 'signup' %}" class="hover:opacity-90">Signup</a>
            {% endif %}
          </nav>
        </div>
      </section>
      <section
        id="mobile-menu"
        class="top-68 justify-content-center absolute hidden w-full origin-top animate-open-menu flex-col bg-black text-5xl"
      >
        <!-- <button class="text-8xl self-end px-6">
        &times;
    </button> -->
        <nav
          class="flex min-h-screen flex-col items-center py-8"
          aria-label="mobile"
        >
          {% if user.is_authenticated %}
          <a
            href="{% url 'show_my_tasks' %}"
            class="w-full py-6 text-center hover:opacity-90"
            >My tasks</a
          >
          <a
            href="{% url 'list_projects' %}"
            class="w-full py-6 text-center hover:opacity-90"
            >My projects</a
          >
          <a
            href="{% url 'logout' %}"
            class="w-full py-6 text-center hover:opacity-90"
            >Logout</a
          >
          {% else %}
          <a
            href="{% url 'login' %}"
            class="w-full py-6 text-center hover:opacity-90"
            >Login</a
          >
          <a
            href="{% url 'signup' %}"
            class="w-full py-6 text-center hover:opacity-90"
            >Signup</a
          >
          {% endif %}
        </nav>
      </section>
    </header>
    {% block content %} {% endblock content %}
    <footer
      id="footer"
      class="lg:absolute sm:static bottom-0 left-0 right-0 mt-8 bg-teal-700 text-xl text-white"
    >
      <section
        class="mx-auto flex max-w-4xl flex-col p-4 sm:flex-row sm:justify-between"
      >
        <address>
          <h2>Blazer's Task-Managers, Inc.</h2>
          555 Planner Way<br />
          Fairfield, New Jersey 12345-5555<br />
          Email:
          <a href="mailto:inquiries@acmerockets.com"
            >Inquiries@BlazersTasks.com</a
          ><br />
          Phone: <a href="tel:+15555555555">(555) 555-5555</a>
        </address>
        <nav class="hidden flex-col gap-2 md:flex" aria-label="footer">
          <a
            href="{% url 'create_project' %}"
            class="hover:opacity-90 text-indigo-700 dark:text-indigo-300"
            >Create Project</a
          >
          <a
            href="{% url 'create_task' %}"
            class="hover:opacity-90 text-indigo-700 dark:text-indigo-300"
            >Create Task</a
          >
          <a
            href="{% url 'logout' %}"
            class="hover:opacity-90 text-indigo-700 dark:text-indigo-300"
            >Logout</a
          >
        </nav>
        <div class="flex flex-col sm:gap-2">
          <p class="text-right">Copyright &copy; <span id="year">2023</span></p>
          <p class="text-right">All Rights Reserved</p>
        </div>
      </section>
    </footer>
  </body>
</html>

projects/templates/projects/create_project.html
{% extends 'base.html' %}

<!---->
{% block title %} Projects {% endblock title %}
<!---->
{% block content %}
<main class="mx-auto max-w-4xl">
  <div
    class="widescreen:section-min-height tallscreen:section-min-height mb-12 scroll-mt-40 items-center justify-center gap-8 p-3"
  >
    <h1
      class="my-6 text-left text-4xl font-bold text-slate-900 dark:text-white sm:text-5xl"
    >
      Create a new project
    </h1>
    {% for error in errors %}
    <p>{{error}} ERROR!</p>
    {% endfor %}
    <form
      autocomplete="off"
      method="post"
      class="items-left mx-auto flex max-w-4xl flex-col gap-4 text-2xl sm:text-3xl"
    >
      {% csrf_token %}

      <input
        autocomplete="false"
        name="hidden"
        type="text"
        style="display: none"
      />

      <label for="name">Name:</label>
      <!--not sure about ID-->
      <input
        type="text"
        id="name"
        name="name"
        required
        minlength="3"
        maxlength="60"
        placeholder="Project Name"
        class="min-w-[240px] w-1/3 rounded-xl border border-solid border-slate-900 p-3 text-xl text-black dark:border-none sm:text-3xl"
      />
      <label for="Description">Description:</label>
      <textarea
        type="text"
        id="description"
        name="description"
        cols="30"
        rows="10"
        required
        placeholder="Tell us about your project..."
        class="min-w-[240px] w-1/3 rounded-xl border border-solid border-slate-900 p-3 text-sm text-black dark:border-none sm:text-sm"
      ></textarea>
      <label for="id_owner">Owner:</label>
      <div class="mt-1">
        <select
          name="owner"
          id="id_owner"
          required
          class="appearance-none min-w-[240px] w-1/3 rounded-xl border border-solid border-slate-900 p-3 text-xl text-black dark:border-none sm:text-3xl"
        >
          <option>Please select</option>
          {% for owner in users %}
          <option value="{{ owner.pk }}">{{ owner.username }}</option>
          {% endfor %}
        </select>
      </div>

      <button
        class="mt-6 w-48 rounded-xl border border-solid border-slate-900 bg-teal-700 p-3 text-white hover:bg-teal-600 active:bg-teal-500 dark:border-none"
      >
        Create
      </button>
    </form>
  </div>
</main>
{% endblock content %}

projects/templates/projects/create_task.html
{% extends 'base.html' %}

<!---->
{% block title %} Tasks {% endblock title %}

<!---->
{% block content %}
<main class="mx-auto max-w-4xl">
  <div
    class="widescreen:section-min-height tallscreen:section-min-height mb-12 scroll-mt-40 items-center justify-center gap-8 p-3"
  >
    <h1
      class="my-6 text-left text-3xl font-bold text-slate-900 dark:text-white sm:text-5xl"
    >
      Create a new task
    </h1>
    <form
      method="post"
      class="items-left mx-auto flex max-w-4xl flex-col gap-4 text-l sm:text-3xl"
    >
      {% csrf_token %}

      <input
        autocomplete="false"
        name="hidden"
        type="text"
        style="display: none"
      />
      <label for="name">Name:</label>
      <!--not sure about ID-->
      <input
        type="text"
        id="name"
        name="name"
        required
        minlength="3"
        maxlength="60"
        placeholder="Task Name"
        class="min-w-[240px] w-1/3 rounded-xl border border-solid border-slate-900 p-1.5 text-l text-black dark:border-none sm:text-3xl"
      />
      <label for="start_date">Start date:</label>
      <!--not sure about ID-->
      <input
        type="date"
        id="start_date"
        name="start_date"
        required
        class="min-w-[240px] w-1/3 rounded-xl border border-solid border-slate-900 p-1.5 text-l text-black dark:border-none sm:text-3xl"
      />
      <label for="due_date">Due date:</label>
      <!--not sure about ID-->
      <input
        type="date"
        id="due_date"
        name="due_date"
        required
        class="min-w-[240px] w-1/3 rounded-xl border border-solid border-slate-900 p-1.5 text-l text-black dark:border-none sm:text-3xl"
      />
      <label for="project">Project:</label>
      <div class="mt-1">
        <select
          name="project"
          id="project"
          required
          class="appearance-none min-w-[240px] w-1/3 rounded-xl border border-solid border-slate-900 p-1.5 text-l text-black dark:border-none sm:text-3xl"
        >
          <option>Please select</option>
          {% for project in projects %}
          <option value="{{ project.pk }}">{{ project.name }}</option>
          {% endfor %}
        </select>
      </div>
      <label for="assignee">assignee:</label>
      <div class="mt-1">
        <select
          name="assignee"
          id="assignee"
          required
          class="appearance-none min-w-[240px] w-1/3 rounded-xl border border-solid border-slate-900 p-1.5 text-l text-black dark:border-none sm:text-3xl"
        >
          <option>Please select</option>
          {% for assignee in assignees %}
          <option value="{{ assignee.pk }}">{{ assignee.username }}</option>
          {% endfor %}
        </select>
      </div>
      <label for="is_completed">Is completed?</label>
      <input type="checkbox" id="is_completed" name="is_completed" />
      <button
        class="mt-6 w-48 rounded-xl border border-solid border-slate-900 bg-teal-700 p-1.5 text-white hover:bg-teal-600 active:bg-teal-500 dark:border-none"
      >
        Create
      </button>
    </form>
  </div>
</main>
{% endblock content %} {% comment %} {% block content %}
<main class="mx-auto max-w-4xl">
  <div>
    <h1>Create a new task</h1>
    <form method="post">
      {% csrf_token %}{{ form.as_p }}
      <button>Create</button>
    </form>
  </div>
</main>
{% endblock content %} {% endcomment %}

projects/templates/projects/list_projects.html
{% extends 'base.html' %}

<!---->
{% block content %}
<!---->
<main class="mx-auto max-w-4xl">
  <div
    class="widescreen:section-min-height tallscreen:section-min-height mb-12 scroll-mt-40 items-center justify-center gap-8 p-3"
  >
    <h1 class="text-3xl font-medium">My Projects</h1>
    <p>
      <a
        href="{% url 'create_project' %}"
        class="text-indigo-700 dark:text-indigo-300"
        >Create a new project ⬅️</a
      >
    </p>
    {% if project_list|length == 0 %}
    <div class="py-8 items-center justify-center text-center">
    <p><h1 class="text-2xl font-medium">You are not assigned to any projects!</h1></p>
    </div>
    <!---->
    {% else %}
    <table class="table-auto max-w-[80%] mt-4">
      <thead class="bg-gray-50 border-b-2 border-gray-200 dark:bg-black">
        <tr>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            Name
            <!--<hr class="mb-2">-->
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            Number of tasks
            <!--<hr class="mb-2">-->
          </th>
        </tr>
      </thead>

      <tbody>
        {% for project in project_list %}
        <tr>
          <td class="p-3 text-sm text-gray-700">
            <a
              href="{% url 'show_project' project.id %}"
              class="dark:text-teal-500 hover:text-indigo-700 dark:hover:text-indigo-300" class="font-bold text-blue-500 hover:underline"
              >☦  {{ project.name }}</a
            >
          </td>
          <td class="p-6 text-sm text-gray-700 dark: dark:text-indigo-500">{{ project.tasks.all|length }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
</main>

{% endblock content %}

projects/templates/projects/project_detail.html
{% extends 'base.html' %}

<!---->
{% block title %} Projects {% endblock title %}
<!---->
{% block content %}
<main class="mx-auto max-w-4xl">
  <div
    class="widescreen:section-min-height tallscreen:section-min-height mb-12 scroll-mt-40 items-center justify-center gap-8 p-3"
  >
    <h1 class="text-3xl font-medium">{{ this_project.name }}</h1>
    <hr />
    <!--STYLE THIS, DUMMY!-->
    <p class="p-3 text-slate-500">{{ this_project.description }}</p>
    <h2 class="text-2xl font-medium">Tasks</h2>
    <!--STYLE???-->
    <p>
      <a
        href="{% url 'create_task' %}"
        class="p-3 text-indigo-700 dark:text-indigo-300 hover:opacity-90"
        >Create a new task ⬅️</a
      >
    </p>
    {% if this_project.tasks.all|length > 0 %}
    <table class="table-auto max-w-[80%] mt-4">
      <thead class="bg-gray-50 border-b-2 border-gray-200 dark:bg-black">
        <tr>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            Name
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            Assignee
          </th>
          <th
            class="max-md:hidden p-3 text-sm font-semibold tracking-wide text-left"
          >
            Start date
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            Due<span class="hidden sm:block"> date</span>
          </th>
          <th
            class="max-md:hidden p-3 text-sm font-semibold tracking-wide text-left"
          >
            Is completed
          </th>
        </tr>
      </thead>
      <tbody>
        {% for task in this_project.tasks.all %}
        <tr>
          {% if task.is_completed %}
          <td class="p-3 text-sm text-gray-700 dark:text-gray-200"><div class="p-1.5 bg-teal-600 rounded-lg sm:dark:bg-black sm:bg-slate-50 bg-opacity-50">
            {{ task.name }}</div>
          </td>
          {% else %}
          <td class="p-3 text-sm text-gray-700 dark:text-gray-200"><div class="p-1.5 bg-orange-600 rounded-lg sm:dark:bg-black sm:bg-slate-50 bg-opacity-50">
            {{ task.name }}
          </td></span>
          {% endif %}
          <td class="p-3 text-sm text-gray-700 dark:text-gray-200">
            {{ task.assignee }}
          </td>
          <td
            class="max-sm:hidden p-3 text-sm text-gray-700 dark:text-gray-200"
          >
            {{ task.start_date|date:"n/j/y" }}
          </td>
          <td class="p-3 text-sm text-gray-700 dark:text-gray-200">
            {{ task.due_date|date:"n/j/y" }}
          </td>
          <td
            class="max-sm:hidden p-3 text-sm text-gray-700 dark:text-gray-200"
          >
            {{ task.is_completed|yesno }}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p class="p-3 text-slate-500">This project has no tasks</p>
    {% endif %}
  </div>
</main>
{% endblock content %}

projects/templates/projects/show_my_tasks.html
{% extends 'base.html' %}

<!---->
{% block content %}
<!---->
<main class="mx-auto max-w-4xl">
  <div
    class="widescreen:section-min-height tallscreen:section-min-height mb-12 scroll-mt-40 items-center justify-center gap-8 p-3"
  >
    <h1 class="text-3xl font-medium">My Tasks</h1>
    {% if my_tasks|length == 0 %}
    <p class="p-3 text-slate-500">You have no tasks</p>
    <!---->
    {% else %}
    <table class="table-auto max-w-[80%] mt-4">
      <thead class="bg-gray-50 border-b-2 border-gray-200 dark:bg-black">
        <tr>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            Name
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            Start date
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            Due date
          </th>
          <th class="p-3 text-sm font-semibold tracking-wide text-left">
            Is completed
          </th>
        </tr>
      </thead>
      <tbody>
        {% for task in my_tasks %}
        <tr>
          <td class="p-3 text-sm text-gray-700 dark:text-gray-200">
            {{ task.name }}
          </td>
          <td class="p-3 text-sm text-gray-700 dark:text-gray-200">
            {{ task.start_date|date:"n/j/y" }}
          </td>
          <td class="p-3 text-sm text-gray-700 dark:text-gray-200">
            {{ task.due_date|date:"n/j/y" }}
          </td>
          <td class="p-3 text-sm text-gray-700 dark:text-gray-200">
            {{ task.is_complete|yesno }}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% endif %}
  </div>
  {% endblock content %}
</main>

theme/templates/base_tw.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>